### ISSUE TITLE
Bug: When handling ExternalName services it should not touch IpFamilyPolicy

### ISSUE THREAD

**Issue by samip5** [tibordp/prefer-dual-stack-webhook#2]
I noticed that if I have an ExternalName service, the mutating webhook tries to do ipFamilyPolicy which is not allowed.

```yaml
apiVersion: v1
kind: Service
metadata:
  name: gitlab-docker
  namespace: networking
spec:
  ports:
    - name: https
      port: 443
  type: ExternalName
  externalName: 192.168.2.33
```

```
The Service "gitlab-docker" is invalid: spec.ipFamilyPolicy: Forbidden: may not be set for ExternalName services
```
